### ISSUE TITLE
if wanna get use different ips for free but don't want free slow proxies

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#53]
install https://1.1.1.1/
when you wanna reset ip you uninstall and reinstall
the ip on whatismyip isn't actually what ms rewards sees when you use it

**Comment by gdrhzrd6e** [comment]
could probably implement something into GitHub workflow cause it supports Linux

**Comment by dmarts05** [comment]
>Changing to using a different DNS provider will not change your IP address.

It is possible that if your IP has changed recently - some DNS servers have updated and know your new IP, but others haven't and don't - this process of "propagation" can take quite some time in some cases.

This could give off the impression that your IP has changed at the point of changeover.

Likewise, if you switched DNS servers and this involved rebooting a router or resetting your connection as part of the change process - a new IP may have been leased out by the ISP in question which would have actually changed the IP, but it still was not caused by the DNS server change.

Source: [StackExchange](https://superuser.com/questions/725493/can-using-a-different-dns-server-effect-ones-ip-address#:~:text=Changing%20to%20using%20a%20different,not%20change%20your%20IP%20address.)

**Comment by gdrhzrd6e** [comment]
it changes something cause i did more than once to be sure

**Comment by gdrhzrd6e** [comment]
resetting my router never works for me always takes whole day

**Comment by gdrhzrd6e** [comment]
what might cloudflare be changing bes
