### ISSUE TITLE
Auto-Redeem Feature: Gift Card localization

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#59]
Hey,

first off all... big thanks to @dmarts05 for this big Update!

But there is one thing that may be a dealbreaker. 

I run this script via Github Action/Workflow. Because Github is hosted on USA IPs, the script also farm all the points from the US-Rewards page. So far so great. If the auto redeem feature work with the "local site" that the script use to earn the Points, you also can only redeem gift cards that available in the US.

For example: Amazon.com instead of amazon.co.uk, amazon.de, amazon.en etc...

My Question: If i have a rewards account outside the US and still wanna use this feature is it possible?

Thanks!

**Comment by MehdiRtal** [comment]
I believe you should use a proxy.

**Comment by DerMuffin** [comment]
The problem with proxies are that many of them work for normal use, but rewards seems to detect when using a proxy or vpn and they just dont accept your login. No matter if the credentials are actually right or wrong.

Thats at least my experience for free proxies i found on a google search

**Comment by Axel3026** [comment]
I live in Argentina and it does not allow me to redeem cards in the United States, once I got an error, and with this program that automates that claim, I will not be able to have RP codes for lol in Latin America, but from the US

**Comment by dmarts05** [comment]
Hi, the redeem feature should work anyways because it uses the same browser session used by the farmer. What I don't know as of now is if those US redeemed cards are only compatible with amazon.com.

I don't really know the answer to this question because I use my own servers for MS farming. Testing might be the only way to know to be honest.

**Comment by dmarts05** [comment]
Ok, so after a bit of research I have found that Amazon Gift Cards are region locked so it might not work. It might not be the case for other rewards.

**Comment by DimaRazb** [comment]
> My Question: If i have a rewards account outside the US and still wanna use this feature is it possible?

You could farm the points in one region and redeem them in another. Tested, worked. The only thing is- it may be a reason to block your account later.

**Comment by dmarts05** [comment]
> > My Question: If i have a rewards account outside the US and still wanna use this feature is it possible?
> 
> You could farm the points in one region and redeem them in another. Tested, worked. The only thing is- it may be a reason to block your account later.

The problem is that the auto-redeem feature will try to redeem these points using a US session which could rise the problems I explained in my previous post.

**Comment by DimaRazb** [comment]
Well- that's the region restrictions. Then you have to switch from shiny Github actions to the hosted scenarios for your region.

**Comment by Axel3026** [comment]
@DimaRazb It's just that you can't, I'm from Argentina, I'm going to have to claim it manually when I reach 6500 points and that's it. If you were a native of the United States with the phone number there, you could claim everything automatically

**Comment by DimaRazb** [comment]
I did some redeems using free numbers from site (there are hundreds of them) like [this](https://receive-sms-free.cc/Free-USA-Phone-Number/18034866798/). I could use the same from Argentina. Never claimed anything automatically btw, only manually.

**Comment by Axel3026** [comment]
What would be good for you in Argentina? If we don't have anything to claim, it's a shitty country with few rewards, luckily I can have free rp @DimaRazb

**Comment by mgrimace** [comment]
> @DimaRazb It's just that you can't, I'm from Argentina, I'm going to have to claim it manually when I reach 6500 points and that's it. If you were a native of the United States with the phone number there, you could claim everything automatically

What about a free tier Oracle virtual server? You could run this headless, but it would be a local server (assuming it’s available in your region), which should allow you to auto redeem things in local currency (?)

**Comment by DerMuffin** [comment]
@DimaRazb The Numbers dont work if you want to unlock a locked account btw.

Anyone knows some numbers that work?

**Comment by DerMuffin** [comment]
@mgrimace Will try that out! Thanks!

**Comment by dmarts05** [comment]
> > @DimaRazb It's just that you can't, I'm from Argentina, I'm going to have to claim it manually when I reach 6500 points and that's it. If you were a native of the United States with the phone number there, you could claim everything automatically
> 
> What about a free tier Oracle virtual server? You could run this headless, but it would be a local server (assuming it’s available in your region), which should allow you to auto redeem things in local currency (?)

I didn't know that! These servers are amazing, thank you very much for sharing this information!

**Comment by mgrimace** [comment]
> I didn't know that! These servers are amazing, thank you very much for sharing this information!

Yeah, it's great! I have one myself as a left-over from tinkering with some other handy scripts, bots, and stuff. 

I use github actions at the moment for this script and haven't tested it on a virtual server, but it should work using the `--headless ` argument. 

You do probably do *not* want to run it with the `--everyday TIME` argument since you're likely connecting via SSH and not leaving the session open/running. That being said you `screen` to keep it running. Likely easier to use `cron` though to automatically run it on a routine schedule... as long as the script has zero human interaction/prompts necessary with the headless argument. 

If there are any prompts, the script may have to be disabled to run it as a cron job automatically on a virtual server. 

Here's a resource for creating the VPS: https://www.youtube.com/watch?v=_9FWri0a9Bo, I just selected a newer version of Ubuntu.

**Comment by dmarts05** [comment]
> 

Thank you for all your help. I have a couple of physical servers running ms farmer and with this I can keep scaling it with more accounts.
